apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-resource-quota
  namespace: apps-prod
spec:
  hard:
    requests.cpu: "32"
    requests.memory: 64Gi
    limits.cpu: "64"
    limits.memory: 128Gi
    pods: "200"
    services: "50"
    persistentvolumeclaims: "30"
    count/ingresses.networking.k8s.io: "20"
